# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: npm i yarn gulp lerna -g
    - run: yarn
    - run: yarn run prerelease && yarn run build:prod
    - name: Npm registry authentication
      run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
    - run: git config --global user.email "grolea@aimelo.com"
    - run: git config --global user.name "grolea"
    - run: lerna publish --yes --force-publish --no-verify-access --exact -m "@Grolea publish %s release" -- --access public